### ISSUE TITLE
Allow key delays for all the keys

### ISSUE THREAD

**Issue by PhoneixS** [Leproide/Linux-G15-Daemon-Logitech-G110-#6]
Although it's nice to have the keys events as fast as they can, sometimes it's better to reproduce the same pace as the original sequence.

I think is better to enable time delay for all the keys and if you don't want it you can set the time to 0 in the configuration file (see #4).

**Comment by Leproide** [comment]
Hi!
Pull request merged.
The code you find in this repository comes from a project not mine that died years ago.
Unfortunately, many fixes have been lost over the years, there are multiple versions that have been lost.
Any contribution is welcome :)
