### ISSUE TITLE
libusb1-1.4.1 not installing

### ISSUE THREAD

**Issue by namedeleted98** [Leproide/Linux-G15-Daemon-Logitech-G110-#7]
when I install libusb with setup.py it says it installs but when I go to the G110 patch it says to install libusb

heres when I run sudo python3 setup.py install

running install
/usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing libusb1.egg-info/PKG-INFO
writing dependency_links to libusb1.egg-info/dependency_links.txt
writing top-level names to libusb1.egg-info/top_level.txt
reading manifest file 'libusb1.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'COPYING'
writing manifest file 'libusb1.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
copying build/lib/libusb1.py -> build/bdist.linux-x86_64/egg
copying build/lib/usb1.py -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/libusb1.py to libusb1.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/usb1.py to usb1.cpython-310.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying libusb1.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying libusb1.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying libusb1.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying libusb1.egg-info/pbr.json -> build/bdist.linux-x86_64/egg/EGG-INFO
copying libusb1.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/libusb1-1.4.1-py3.10.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing libusb1-1.4.1-py3.10.egg
Removing /usr/local/lib/python3.10/site-packages/libusb1-1.4.1-py3.10.egg
Copying libusb1-1.4.1-py3.10.egg to /usr/local/lib/python3.10/site-packages
libusb1 1.4.1 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.10/site-packages/libusb1-1.4.1-py3.10.egg
Processing dependencies for libusb1==1.4.1
Finished processing dependencies for libusb1==1.4.1

**Comment by defautluser0** [comment]
did you ever fix this problem?
